language: php
sudo: false
dist: trusty

env:
  global:
    - RUN_PHPCS="no"
    - RUN_PHPUNIT="yes"
    - COMPOSER_FLAGS="--prefer-stable"

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.2
      env: RUN_PHPCS="yes"
    - php: 7.3
    - php: 7.3
      # This empty flag removes the prefer-stable switch to cause dev dependencies to be installed
      env: COMPOSER_FLAGS=""
    - php: 7.4
    - php: nightly
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer update $COMPOSER_FLAGS
  - ./vendor/bin/phpcs --config-set installed_paths $(pwd)

script:
  - if [[ $RUN_PHPUNIT == "yes" ]]; then ./vendor/bin/phpunit --filter Dazzle vendor/squizlabs/php_codesniffer/tests/AllTests.php; fi
  - if [[ $RUN_PHPCS == "yes" ]]; then ./vendor/bin/phpcs -sp --extensions=php --ignore=*/vendor/* --standard=Dazzle */ .; fi

notifications:
  email: false
